### PR TITLE
fix: header event emits indexed and unindexed header

### PR DESCRIPTION
**Pull request by prestwich**
indexed structs are serialized and hashed, and the original data is not included in the event. This adds a non-indexed Header struct param alongside, so that we keep access to the header data

### CODE REVIEW

**Comment by anna-carroll** [comment]
i think maybe let's just do non-indexed?

**Comment by prestwich** [comment]
having both allows us to still use it as a topic to find the specific event that admitted that header

**Comment by anna-carroll** [comment]
yes but i'm wondering in what circumstances we would have the exact header information beforehand and want to use it to query the event. `confirmBy` field in the header in particular means that there isn't a situation where we'd be able to query for a header without knowing the specific information about that header beforehand. 

i'm wondering if there's a way we could serve the need of "i know about a header, i want to find the event" while also servicing other more general & useful things. 

i think it would be nice to have the following indexed:
- uint256 rollupChainId;
- uint256 sequence;

perhaps we break out the header info into individual event params and index those?

**Comment by anna-carroll** [comment]
would we wanna do 

```
event BlockSubmitted(address indexed sequencer, uint256 indexed rollupChainId, uint256 indexed sequence, uint256 confirmBy, uint256 gasLimit, address rewardAddress, bytes32 blockDataHash);
```

just to avoid paying for re-emitting `rollupChainId` and `sequence` unnecessarily

**Comment by prestwich** [comment]
this is fine. let's ship it

**Review by anna-carroll — APPROVED** [review]

**Pull request merged**
